algoritmo "porcentagem"
var
tot, val, nul, branco: inteiro
inicio
escreva ("Total de eleitores: ")
leia (tot)
escreva ("Votos Válidos: ")
leia (val)
escreva ("Votos Nulos: ")
leia (nul)
escreva ("Votos em branco: ")
leia (branco)
escreval
escreva ("Porcentagem de votos válidos: ", val / tot * 100)
escreva ("%")
escreval
escreva ("Porcentagem de votos Nulos: ", nul / tot * 100)
escreva ("%")
escreval
escreva ("Porcentagem de votos em branco: ", branco / tot * 100)
escreva ("%")
fimalgoritmo
