algoritmo "semnome"
// Função :
// Autor :
// Data : 5/4/2013
// Seção de Declarações 
var
num, maiornum:real
varcontrole, loop:inteiro
inicio
escreva("Quantidade de repetições: ")
leia (loop)
para varcontrole de 1 ate loop passo 1 faca
escreva("Número: ")
leia (num)
  se (num > maiornum) entao
  maiornum<- num
  senao
  maiornum<- maiornum
  fimse
fimpara
escreva ("O maior de todos é ", maiornum)
fimalgoritmo
