algoritmo "semnome"
// Função :
// Autor :
// Data : 3/9/2013
// Seção de Declarações 
var
num1, num2: real
inicio
escreva ("Escreva o valor 1: ")
leia (num1)
escreva ("Escreva o valor 2: ")
leia (num2)
escreval
se (num1 > num2) entao
escreva ("Sequência crescente:", num2 ," ,", num1)
fimse
se (num2 > num1) entao
escreva ("Sequência crescente:", num1 ," ,", num2)
fimse
se (num1 = num2) entao
escreva ("Os Números são iguais")
fimse
fimalgoritmo
