algoritmo "semnome"
// Função :
// Autor :
// Data : 3/17/2013
// Seção de Declarações 
var
salario, finan, calc:real
inicio
escreva ("Informe seu salário: ")
leia (salario)
escreva ("Informe o valor do financiamento pretendido: ")
leia (finan)
calc<- salario * 5
se (calc>=finan) entao
escreva ("Financiamento Concedido")
senao
escreva ("Financiamento Negado")
fimse
escreval
escreva ("Obrigado por nos consultar.")
fimalgoritmo
